#### 1. Import the numpy package under the name `np` (★☆☆)


In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [3]:
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/opt/anaconda3/envs/codeacademy/lib/python3.12/site-packages/numpy/version.py'>
<function show at 0x1072bc040>


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array

In [8]:
np.size(a)

10

#### 5. How to get the documentation of the numpy add function from the command line?

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

# 6
Create a null vector of size 10 but the fifth value which is 1

In [13]:
b =np.zeros(10)
b[5] = 1

print(b)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


# 7. 
Create a vector with values ranging from 10 to 49


In [15]:
c = np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8. Reverse a vector (first element becomes last)

In [16]:
print(c[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 9. Create a 3x3 matrix with values ranging from 0 to 8 

In [20]:
d = np.arange (0,9)
print(d.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [22]:
e = [1,2,0,0,4,0]
np.nonzero(e)

(array([0, 1, 4]),)

# 11. Create a 3x3 identity matrix 


In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12. Create a 3x3x3 array with random values

In [ ]:
np.random.random((3,3,3))

array([[[0.03881422, 0.25980471, 0.89318945],
        [0.07569076, 0.10206313, 0.75806153],
        [0.25041929, 0.95879703, 0.11205915]],

       [[0.86524935, 0.02125481, 0.72388252],
        [0.78908643, 0.90282436, 0.46976794],
        [0.44231356, 0.44194519, 0.95804451]],

       [[0.23440857, 0.24100708, 0.43457905],
        [0.95544059, 0.76066114, 0.08245081],
        [0.16547304, 0.64193258, 0.26931011]]])

# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [38]:
f = np.random.random((10,10))
# print(np.max(f))
# print (np.min(f))
fmin, fmax = f.min(), f.max()
print(fmin, fmax)

0.002168859651432542 0.988912197750011


# 14. Create a random vector of size 30 and find the mean value

In [50]:
g = np.random.random(30)
np.mean(g)
print(np.mean(g))


0.482659382441531


# 15. Create a 2d array with 1 on the border and 0 inside 

In [89]:
f = np.array([[1,1,1],
             [1,0,1],
             [1,1,1]])

print (f)

g = np.ones((6, 6))
print(g)
g[1: -1, 1:-1] = 0 
print(g)

[[1 1 1]
 [1 0 1]
 [1 1 1]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


# 16. How to add a border (filled with 0's) around an existing array?

In [113]:
f2 = np.ones((5,5))

# print(np.pad(f2, (0,0))
padded = np.pad(f2, pad_width=1, constant_values= 0 )

print(f2)
print(padded)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [115]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [141]:
# g = np.arange(25).reshape((5,5))
# print(g)

# diag = np.diag(g, k = -1)
# # diag = [1,2,3,4]

# print(diag)
arange4 = np.arange(4)
print(arange4 +1) 

# +1 so it doesn't start with 0
g2 = np.diag(1 + np.arange(4), k =-1)
print(g2)
np.shape(g2)


[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


(5, 5)

 # 20
 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [150]:
h = np.unravel_index(99,(6,7,8))

print(h)

(np.int64(1), np.int64(5), np.int64(3))
